services:

  drupal:
    image: drupal-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - TARGET_ENV=${TARGET_ENV}
    env_file:
      - .env
    volumes: 
      - "${DAO_PROJECT_DIR}:/var/www/html:delegated"

  nginx:
    image: drupal-nginx
    build:
      context: ./docker/nginx
    ports: [ "${DAO_PORT_NGINX}:8080" ]
    volumes: [ "${DAO_PROJECT_DIR}:/var/www/html/:delegated" ]

  mysql:
    image: mysql:8.0
    ports: [ "${DAO_PORT_MYSQL}:3306" ]
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes: [ "/var/lib/mysql" ]